allowBuilds:
  '@firebase/util': set this to true or false
  '@progress/kendo-licensing': set this to true or false
  canvas: set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
